"""modify table

Revision ID: 68340cc50dfb
Revises: 821a0db0aba6
Create Date: 2018-04-19 14:42:39.067490

"""

# revision identifiers, used by Alembic.
revision = '68340cc50dfb'
down_revision = '821a0db0aba6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kk_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_n', sa.Integer(), nullable=True),
    sa.Column('item_n', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pay_n', sa.String(length=64), nullable=True),
    sa.Column('create_t', sa.DateTime(), nullable=True),
    sa.Column('pay_t', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['item_n'], ['kk_items.target_n'], ),
    sa.ForeignKeyConstraint(['set_n'], ['kk_sets.target_n'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kk_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kk_orders_pay_n'), 'kk_orders', ['pay_n'], unique=True)
    op.drop_table('kk_order')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kk_order',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('set_n', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('item_n', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pay_n', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('create_t', mysql.DATETIME(), nullable=True),
    sa.Column('pay_t', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_n'], [u'kk_items.target_n'], name=u'kk_order_ibfk_1'),
    sa.ForeignKeyConstraint(['set_n'], [u'kk_sets.target_n'], name=u'kk_order_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'kk_users.id'], name=u'kk_order_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_kk_orders_pay_n'), table_name='kk_orders')
    op.drop_table('kk_orders')
    ### end Alembic commands ###
