"""initial migrate

Revision ID: 821a0db0aba6
Revises: None
Create Date: 2018-04-19 14:39:35.635615

"""

# revision identifiers, used by Alembic.
revision = '821a0db0aba6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kk_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('kk_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_n', sa.Integer(), nullable=True),
    sa.Column('type', sa.SMALLINT(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('notice', sa.Text(), nullable=True),
    sa.Column('create_t', sa.DateTime(), nullable=True),
    sa.Column('modify_t', sa.TIMESTAMP(), nullable=True),
    sa.Column('market_p', sa.Integer(), nullable=True),
    sa.Column('discount_p', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kk_sets_target_n'), 'kk_sets', ['target_n'], unique=True)
    op.create_table('kk_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('union_id', sa.String(length=64), nullable=True),
    sa.Column('open_id', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.SMALLINT(), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.SMALLINT(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('register_t', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kk_users_union_id'), 'kk_users', ['union_id'], unique=True)
    op.create_table('kk_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('adminname', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.SMALLINT(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['kk_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kk_admins_adminname'), 'kk_admins', ['adminname'], unique=True)
    op.create_index(op.f('ix_kk_admins_email'), 'kk_admins', ['email'], unique=True)
    op.create_table('kk_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_n', sa.Integer(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('type', sa.SMALLINT(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_t', sa.DateTime(), nullable=True),
    sa.Column('modify_t', sa.TIMESTAMP(), nullable=True),
    sa.Column('market_p', sa.Integer(), nullable=True),
    sa.Column('discount_p', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['kk_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kk_items_target_n'), 'kk_items', ['target_n'], unique=True)
    op.create_table('kk_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_n', sa.Integer(), nullable=True),
    sa.Column('item_n', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pay_n', sa.String(length=64), nullable=True),
    sa.Column('create_t', sa.DateTime(), nullable=True),
    sa.Column('pay_t', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['item_n'], ['kk_items.target_n'], ),
    sa.ForeignKeyConstraint(['set_n'], ['kk_sets.target_n'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kk_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kk_order_pay_n'), 'kk_order', ['pay_n'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kk_order_pay_n'), table_name='kk_order')
    op.drop_table('kk_order')
    op.drop_index(op.f('ix_kk_items_target_n'), table_name='kk_items')
    op.drop_table('kk_items')
    op.drop_index(op.f('ix_kk_admins_email'), table_name='kk_admins')
    op.drop_index(op.f('ix_kk_admins_adminname'), table_name='kk_admins')
    op.drop_table('kk_admins')
    op.drop_index(op.f('ix_kk_users_union_id'), table_name='kk_users')
    op.drop_table('kk_users')
    op.drop_index(op.f('ix_kk_sets_target_n'), table_name='kk_sets')
    op.drop_table('kk_sets')
    op.drop_table('kk_roles')
    ### end Alembic commands ###
